groups:
  - name: VoteIndexerPackage
    rules:
      # - alert: VoteIndexerSyncSlow
      #   expr: (time() - cvms_consensus_vote_latest_index_pointer_block_timestamp) > 300
      #   for: 30s
      #   labels:
      #     severity: warning
      #   annotations:
      #     summary: The Vote Indexer Package sync is slow to sync blocks for {{ $labels.chain_id }}

      # - alert: IncreaseRecentConsensusVoteMiss
      #   expr: increase(cvms_consensus_vote_recent_miss_counter[1m]) > 15
      #   for: 30s
      #   labels:
      #     severity: critical
      #   annotations:
      #     summary: The validator is missing too many votes in the consensus for {{ $labels.chain_id }}
