# NOTE: Customize this variables by your needs
# 1. network mode:
#   ex) monikers: ['all']
#   des) This will enable network mode to monitor all validators status in the blockchain network
# 
# 2. validator mode:
#   ex) monikers: ['Cosmostation1', 'Cosmostation2']
#   des) This will enable validator mode for whitelisted specific validators
monikers: ['all']

# If the user is a blockchain network maintainer, they will want to operate on one own chain.
chains: 
    # NOTE: display name will be used only this config to indicate followed arguments to communicate internal team members
  - display_name: 'cosmos'
    # NOTE: chain_id is a KEY to find applicable packages in support_chains list. YOU SHOULD MATCH CORRECT CHAIN ID!
    chain_id: cosmoshub-4 
    # NOTE: these addresses will be used for balance usage tracking such as validator, broadcaster or something.
    tracking_addresses:
      - 'cosmos1xxx'
      - 'cosmos1xxx'
      - 'cosmos1xxx'
    nodes:
      # NOTE: currently grpc endpoint doens't support ssl
      - rpc: 'http://localhost:26657'
        api: 'http://localhost:1337'
        grpc: 'localhost:9090'

      - rpc: 'http://localhost:26657'
        api: 'http://localhost:1337'
        grpc: 'localhost:9090'

      - rpc: 'http://localhost:36657'
        api: 'http://localhost:1337'
        grpc: 'localhost:9090'
